### ISSUE TITLE
Craft 3 support?

### ISSUE THREAD

**Issue by j-greig** [supercool/buttonbox#15]
Hiiii, just wondering if a Craft 3 version is in the pipeline?

**Comment by supercooljames** [comment]
Hi James

We’re a little bit behind on Craft 3 dev

The plan is to port Button Box, and a few of our other plugins over.
Likely to be Q2 2018 before we get on to it this end.

James


---

**Comment by j-greig** [comment]
No worries, thanks for the update.

**Comment by askogrand** [comment]
I too would love to get my hands on button box for craft3. Good to know its slated.

**Comment by bossanova808** [comment]
Ditto here.  Commenting just to follow for updates :)

**Comment by bossanova808** [comment]
Oh never mind, I see it's actually there...sorry for the noise.  Any plans to add this to the plugin store?

**Comment by Nav33d** [comment]
@bossanova808 It is in the Craft plugin store :)

**Comment by bossanova808** [comment]
Right - it was just this that fooled me:

![image](https://user-images.githubusercontent.com/731309/40954622-b7eba9f6-68c8-11e8-9892-8bcc57c2309e.png)

I know there's a place you can do a PR to get that updated but I can't find it now...
