### ISSUE TITLE
[Craft 3] Installation via composer needs a release added to packagist?

### ISSUE THREAD

**Issue by john-henry** [supercool/buttonbox#16]
I believe, but could be wrong but does this need to be added to packagist?

Otherwise I get the following

> [InvalidArgumentException]
>   Could not find a matching version of package supercool/buttonbox. Check the
>    package spelling, your version constraint and that the package is availabl
>   e in a stability which matches your minimum-stability (stable).

**Comment by Nav33d** [comment]
Hi John,

I have just tagged a release 2.0.0 for Craft CMS 3 and you should be able to install it using composer `composer require supercool/buttonbox`

Many thanks
