### ISSUE TITLE
Mulitsite error normalizeValue

### ISSUE THREAD

**Issue by pieter-janDB** [supercool/buttonbox#25]
Hi, 

I updated a craft 3 site to be multisite. When setting up a multisite and enabling current sections for this new site, Craft will try to generate new entries that are the same as in the main site.

This gives errors on migrating the buttonbox field (I used buttons and colours).

I disabled the plugin and was able to generate my entries for the new site. After re-enabling the plugin I saw that I was not able to save my entries with a buttonbox field.

Upon looking through the code I found that line 102 in the normalizeValue function 
`$value = reset($selectedValues) ?: null;`
is causing the issue by setting $value not to a string but an array. 

When logging the $value passed to normalizeValue I see that it receives the following:

`object(craft\fields\data\SingleOptionFieldData)#706 (4) { ["_options":"craft\fields\data\SingleOptionFieldData":private]=> array(2) { [0]=> object(craft\fields\data\OptionData)#700 (3) { ["label"]=> string(5) "Links" ["value"]=> string(4) "left" ["selected"]=> bool(false) } [1]=> object(craft\fields\data\OptionData)#699 (3) { ["label"]=> string(6) "Rechts" ["value"]=> string(5) "right" ["selected"]=> bool(true) } } ["label"]=> string(6) "Rechts" ["value"]=> string(5) "right" ["selected"]=> bool(true) }`

After casting this to the array and using the reset function on this value the value now is:

`array(4) { ["craft\fields\data\SingleOptionFieldData_options"]=> array(2) { [0]=> object(craft\fields\data\OptionData)#700 (3) { ["label"]=> string(5) "Left" ["value"]=> string(4) "left" ["selected"]=> bool(false) } [1]=> object(craft\fields\data\OptionData)#699 (3) { ["label"]=> string(6) "Right" ["value"]=> string(5) "right" ["selected"]=> bool(true) } } ["label"]=> string(6) "Right" ["value"]=> string(5) "right" ["selected"]=> bool(true) } array(2) { [0]=> object(craft\fields\data\OptionData)#700 (3) { ["label"]=> string(5) "Left" ["value"]=> string(4) "left" ["selected"]=> bool(false) } [1]=> object(craft\fields\data\OptionData)#699 (3) { ["label"]=> string(6) "Rechts" ["value"]=> string(5) "right" ["selected"]=> bool(true) } }`

Commenting out the `$value = reset($selectedValues) ?: null;` line seems to work allright  but I rather not fiddle in your source code without knowing the reasoning behind these sets..

Thanks for reading,
Related issue: https://github.com/supercool/buttonbox/issues/24

**Comment by alexhillel** [comment]
I'm running into this issue too.
