### ISSUE TITLE
Allow Image Button label to be centered below the image instead of to the right.

### ISSUE THREAD

**Issue by proimage** [supercool/buttonbox#40]
Here's what it looks like when you show the label:
![image](https://user-images.githubusercontent.com/1027523/172145220-9666a4a2-97b1-4802-87d6-32f02b0a7fe5.png)

Here's how I'd like it to look like:
![image](https://user-images.githubusercontent.com/1027523/172145484-988d53cf-5a24-490e-91c8-4895d22e9ed1.png)

An option to toggle between the two layouts would be great. Thanks!

**Comment by proimage** [comment]
...pretty please? ;)

**Comment by engram-design** [comment]
There's a lot that needs revamping in this plugin, but I'll get to that later.

Updated for the next release. To get this early, run `composer require verbb/buttonbox:"dev-craft-4 as 4.2.1"`.

**Comment by proimage** [comment]
That works great, thanks Josh!
