### ISSUE TITLE
Undefined variable $cssColour

### ISSUE THREAD

**Issue by DenyEs** [supercool/buttonbox#42]
Editing any entry with a buttonbox field on version 3.0.1 results in 'Undefined variable $cssColour' error being presented. I downgraded a plugin back to 3.0.0 and this version works fine.

**Steps to reproduce**
1. Create a buttonbox field
2. Assign field to the entry type
3. Attempt to access entry in the CMS

- Plugin version: 3.0.1
- Craft version: 3.7.44
- Multi-site: No

**Comment by engram-design** [comment]
Fixed in [3.0.2](https://github.com/verbb/buttonbox/releases/tag/3.0.2)
