### ISSUE TITLE
No Options Displayed for "Buttons" Field Type

### ISSUE THREAD

**Issue by richhayler** [supercool/buttonbox#43]
**Description**
Creating a new "Button Box" field and selected "Button" from the field type dropdown should show options to add buttons (handle, label etc) but no options are displayed.

<img width="480" alt="CleanShot 2022-06-21 at 12 34 23@2x" src="https://user-images.githubusercontent.com/2505643/174704472-36b05ad5-ed7a-4afb-97bd-7e222223a8c9.png">

**Steps to reproduce**
1. Add a new field
2. Select "Button Box - Buttons"

**Additional info**
- Plugin version: 4.0.1
- Craft version: 4.0.4
- Multi-site: Yes

**Comment by engram-design** [comment]
Fixed in [4.0.2](https://github.com/verbb/buttonbox/releases/tag/4.0.2)

**Comment by richhayler** [comment]
Thanks Josh! And thank you for updating the Button Box plugin for Craft 4. It’s great that you guys have picked up the Supercool plug-ins.
