### ISSUE TITLE
Entry save error relating to languages on Craft 4

### ISSUE THREAD

**Issue by shep-cc** [supercool/buttonbox#44]
**Description**
When attempting to save an entry with ButtonBox fields, it fails with the error message 'Couldn't save entry'.
The error is related to fields with translation.

Yii Debug log shows:
```
The message file for category 'buttonbox' does not exist: /app/vendor/verbb/buttonbox/src/translations/es-ES/buttonbox.php Fallback file does not exist as well: /app/vendor/verbb/buttonbox/src/translations/es/buttonbox.php
```

**Steps to reproduce**
1. On Craft 4.0 add a ButtonBox field that is set to 'Translate for each site' to an entry type
2. Ensure at least one additional site is enabled for that Section with a different language
3. Save the entry

**Additional info**
- Plugin version: dev-craft-4
- Craft version: Craft Pro 4.0.4
- Multi-site: Yes

**Additional context**

**Comment by engram-design** [comment]
Pretty sure that warning is unrelated, it's just saying we don't supply an `es` translation for the plugin. I'm sure there's a bunch more other plugins that don't have translations either.

I can't replicate this though. There should be no reason button box won't work with multi-sites either.

Can you clear out your log files, in `/storage/log` then re-save the entry to get the error, and have a look in your log files for any errors?

**Comment by shep-cc** [comment]
Thanks @engram-design - this turned out to be a bit of a red herring, and was more related to the way our Neo blocks had migrated to Craft 4. Closing the issue.
