### ISSUE TITLE
Error: array must be compatible with craft\fields\BaseOptionsField::translatedOptions

### ISSUE THREAD

**Issue by bartdepotter** [supercool/buttonbox#53]
### Describe the bug

After updating to Craft 4.4.1 I got the following error with buttonbox.

Declaration of verbb\buttonbox\fields\Colours::translatedOptions(bool $encode = false): array must be compatible with craft\fields\BaseOptionsField::translatedOptions(bool $encode = false, mixed $value = null, ?craft\base\ElementInterface $element = null): array

This is solved by changing line 161 on /app/www/vendor/verbb/buttonbox/src/fields/Colours.php to 

    `protected function translatedOptions(bool $encode = false, mixed $value = null, ?ElementInterface $element = null): array`

### Steps to reproduce

1. Update from craft 4.3.8.2 to Craft 4.4.1

### Craft CMS version

4.4.1

### Plugin version

4.1.0

### Multi-site?

No

**Comment by engram-design** [comment]
This has already been [reported](https://github.com/verbb/buttonbox/issues/52) and fixed in [4.2.0](https://github.com/verbb/buttonbox/releases/tag/4.2.0)
