### ISSUE TITLE
Upgrade to 4.4.1 error

### ISSUE THREAD

**Issue by wmdhosting** [supercool/buttonbox#54]
### Describe the bug

![button](https://user-images.githubusercontent.com/76176291/224368461-85499caf-9807-4e41-954c-75af660fa227.png)

### Steps to reproduce

1. Upgrade to last version 4.4.1

### Craft CMS version

Craft Pro 4.3.9

### Plugin version

4.1.0

### Multi-site?

Yes

**Comment by tigerchick** [comment]
Just got the exact same error when performing a big upgrade from Craft 3 / Buttonbox 3.1.1

**Comment by tigerchick** [comment]
Fix: require 4.2.0 in your composer.json then run `composer update`
https://github.com/verbb/buttonbox/issues/53#issuecomment-1463564873

**Comment by engram-design** [comment]
Please search for existing issues before posting new ones https://github.com/verbb/buttonbox/issues/53, https://github.com/verbb/buttonbox/issues/52 as there's already an update available https://github.com/verbb/buttonbox/releases/tag/4.2.0
