### ISSUE TITLE
Error after updating to Craft 4.4.2

### ISSUE THREAD

**Issue by jegra** [supercool/buttonbox#55]
### Describe the bug

After updating from Craft 4.3.8.2 to 4.4.2, our site will no longer load -- we hit an error on both the front end display, and the backend admin area.   The error message is:  
Declaration of verbb\buttonbox\fields\Colours::translatedOptions(bool $encode = false): array must be compatible with craft\fields\BaseOptionsField::translatedOptions(bool $encode = false, mixed $value = null, ?craft\base\ElementInterface $element = null): array

in /Users/xxxxxx/site/vendor/verbb/buttonbox/src/fields/Colours.php   at line 161

### Steps to reproduce

1. upgrade from Craft 4.3.8.2 to Craft 4.4.2, with buttonbox 4.1 installed
2. try accessing the website, either via frontend, or backend admin area.  CLI tool also non-functional.

### Craft CMS version

4.4.2

### Plugin version

4.1

### Multi-site?

Yes

**Comment by engram-design** [comment]
Please search for existing issues before posting new ones as this has been raised multiple times in https://github.com/verbb/buttonbox/issues/54, https://github.com/verbb/buttonbox/issues/53 and https://github.com/verbb/buttonbox/issues/52.

Refer to the Craft 4.4 compatible version https://github.com/verbb/buttonbox/releases/tag/4.2.0 that fixes this.

**Comment by jegra** [comment]
Thanks @engram-design ! That got it sorted.
