### ISSUE TITLE
Colour button label doesn't pass contrast

### ISSUE THREAD

**Issue by mightyfineyall** [supercool/buttonbox#56]
### Describe the bug

The label for the colour button over the default matrix block colour doesn't remotely pass ADA contrast:

![image](https://user-images.githubusercontent.com/48531847/233653506-1c86fae4-15ee-4e9a-9347-54c89ddf54a9.png)

[https://www.myndex.com/apca/?BG=f3f7fc&TXT=c2c4c5&DEV=G4g&BUF=A22](url)

.buttonbox__btn in buttonbox.css just needs to be color:#000000 or similar instead of #c2c4c5

### Steps to reproduce

1. Add a Button Box - Colours field
2. Try to look at it!

### Craft CMS version

4.4.7.1

### Plugin version

4.2.0

### Multi-site?

No

**Comment by engram-design** [comment]
Yeah, that's pretty gross. Fixed for the next release. To get this early, run `composer require verbb/buttonbox:"dev-craft-4 as 4.2.0"`

**Comment by engram-design** [comment]
Updated in [4.2.2](https://github.com/verbb/buttonbox/releases/tag/4.2.0).
