### ISSUE TITLE
Colours field is not keyboard accessible

### ISSUE THREAD

**Issue by JezDriver** [supercool/buttonbox#57]
### Describe the bug

When using the keyboard to navigate through the fields, the colours field is skipped over completely, making it inaccessible to both keyboard and screenreader users.

### Steps to reproduce

1. Create a Button Box - Colours field
2. Add it to a section/global set
3. Edit an instance of that section/global set
4. Bring focus to a field before the Colours field
5. Continue pressing tab until you reach the Colours field
6. You'll find the tab focus skips the Colours field

### Craft CMS version

4.4.14

### Plugin version

4.2.0

### Multi-site?

No

### Additional context

Clicking the Label for the field should use bring focus to the field, but doesn't.

The label issue is also present on the 'Button Box - Buttons' field - while they are keyboard accessible, clicking the label doesn't bring focus to the radio buttons.

**Comment by engram-design** [comment]
Fixed in [4.2.3](https://github.com/verbb/buttonbox/releases/tag/4.2.3)
