### ISSUE TITLE
First Button Box - Buttons auto checks 1st item even with default selected

### ISSUE THREAD

**Issue by AmandaLutzTO** [supercool/buttonbox#58]
### Describe the bug

I have a matrix field to allow users to create different sections of content. In each section I use Button Box - Buttons to allow user to select background image. 

None of the options are set to be default in setting but in the Entry, the first option is always checked by default. 
If I select an option to be default (ie the last item) the correct item is checked by default.

In the mean time I'll add a default "none" option but I don't want this to be a mandatory field. The user should have the option of not selecting anything.

I've done the same type of set up in craft 3 with the craft-3 branch and it worked fine.

### Steps to reproduce

1. Craft 4, plugin 4.2
2. Create Button Box field with multiple options
3. Do NOT select a default option
4. Create new entry that include the Button Box field

### Craft CMS version

4.4.16.1

### Plugin version

4.2.0

### Multi-site?

No

### Additional context

- I created a test Button Box - Buttons field on it's own (not in matrix) and same result, 1st item checked with no default selected.
- I tried all the Button Box types (Colours, Text Size, Width) and it's always the same. The 1st item is always checked although there isn't a default option.

**Comment by engram-design** [comment]
I have checked in the Craft 3 branch, and that does auto-select the first button? But I agree, I don't believe it should.

Fixed in [3.1.2](https://github.com/verbb/buttonbox/releases/tag/3.1.2) and [4.2.1](https://github.com/verbb/buttonbox/releases/tag/4.2.1)
