### ISSUE TITLE
Fields forcefully overwrite value with default when element is fresh

### ISSUE THREAD

**Issue by d--j** [supercool/buttonbox#59]
### Describe the bug

In their `inputHtml` methods the Buttonbox fields unconditionally set the value to the default value when the field's `isFresh` method returns `true`.

See e.g. https://github.com/verbb/buttonbox/blob/fd1d71a49fc3cdf719e68cd5f9d9fe1fd590feae/src/fields/Buttons.php#L169-L171

This is not how the CraftCMS build-in fields do things. And it is also not what the Neo plugin expects.

E.g. Neo sets the `isFresh` of fields when it renders fields for new or cloned blocks. See:

https://github.com/spicywebau/craft-neo/blob/25b2502f717224b6480352564eb96327db5867f7/src/services/Blocks.php#L72-L74

Have a look at the CraftCMS's Dropbox field. They set the default value when the value is invalid:

https://github.com/craftcms/cms/blob/fc3cc36e151018dbf28f315cc9d38a9ad50f283f/src/fields/Dropdown.php#L79-L93

A value is invalid when it is not found in the options. This invalid value handling also is missing in the Buttonbox fields. E.g. when an option gets removed, you should set the value to the default value in `inputHtml`.

### Steps to reproduce

1. Have a ButtonBox field inside a Neo field block
2. Create a Neo block. Change the ButtonBox field to something other than the default.
3. Clone this Neo block. The ButtonBox field will revert to its default value.

or

1. Create a ButtonBox Buttons field with two options "one" and "two". Include this field in a section.
2. Create/update an entry of this section and set the ButtonBox Buttons field to "two".
3. Alter the ButtonBox field, remove the option "two"
4. Go to the edit screen of the entry that you created in step 2. The field will be broken.

### Craft CMS version

Craft Pro 4.5.6.1

### Plugin version

4.2.1

### Multi-site?

No

### Additional context

Neo 3.9.4

Related issues #38, #51, #37

**Comment by engram-design** [comment]
I've been meaning to address this for some time, and it's a carry-over from the previous developers and is decidedly against the norm.

I've given things a good cleanup in [4.2.2](https://github.com/verbb/buttonbox/releases/tag/4.2.2)
