### ISSUE TITLE
Value for button cannot be blank

### ISSUE THREAD

**Issue by since1976** [supercool/buttonbox#6]
I have found that if I leave a value as blank for a button for a field that is set as required the entry won't save.

![screen shot 2014-12-30 at 11 29 59 am](https://cloud.githubusercontent.com/assets/90833/5573818/3dd9a218-9017-11e4-9e7c-5343dbcdd941.png)

In my instance I have a button type field that has the options of Standard (default), Outline or Link. It would be nice if the default type could have a blank value so if I ever need change the base class from btn to button it can be done in the template.

**Comment by joshangell** [comment]
Off the top of my head I'm not quite sure why that is actually happening - does a blank value work if the field is _not_ required?

**Comment by since1976** [comment]
Yes the entry saves if the field isn't required and is supplied with a blank value.
