### ISSUE TITLE
Preview reload bug after changing "Button Box - Colours" Field

### ISSUE THREAD

**Issue by thomasbendl** [supercool/buttonbox#60]
### Describe the bug

after selecting a color in preview mode, it is not reloaded

### Steps to reproduce

1.  create "Button Box - Colours" Filed with x Options
2. add it to a section
3. open preview mode
4. preview is not reloaded after changing the colors

### Craft CMS version

4.7.1

### Plugin version

4.2.0

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [4.2.3](https://github.com/verbb/buttonbox/releases/tag/4.2.3)
