### ISSUE TITLE
Can't select a color after creating a new Neo block

### ISSUE THREAD

**Issue by alexmillman23** [supercool/buttonbox#61]
### Describe the bug

We have a Neo field with a `Button Box - Colours` field inside. On an entry, when a new block is created, the dropdown of the Colours field does not updated the selected value when clicked. If we save the entry first, we can then update the field value.

### Steps to reproduce

1. Add Button Box - Colours field to a Neo field
2. Add Neo block with the Colour field in the Entry edit screen
3. Try to change a Colour

### Craft CMS version

4.7.2.1

### Plugin version

4.2.3

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/buttonbox:"dev-craft-4 as 4.2.3"`

**Comment by alexmillman23** [comment]
Thank you for the quick fix!

**Comment by engram-design** [comment]
Fixed in [4.2.4](https://github.com/verbb/buttonbox/releases/tag/4.2.4)
