### ISSUE TITLE
Too few arguments to function craft\fields\BaseOptionsField::normalizeValue()

### ISSUE THREAD

**Issue by akiraWalk** [supercool/buttonbox#63]
### Describe the bug

Hey guys, i've done a migration from Craft 4 to 5 with no issues. Started editing an existing Button Box field and upon saving I got the error "ArgumentCountError
Too few arguments to function craft\fields\BaseOptionsField::normalizeValue(), 1 passed in /home/client/craft/vendor/verbb/buttonbox/src/fields/Buttons.php on line 153 and exactly 2 expected"

### Steps to reproduce

1. Go to an entry and load in block that has Button Box as a field type
2. Clicked the cog to edit
3. Modified the Value column
<img width="918" alt="Screenshot_1" src="https://github.com/verbb/buttonbox/assets/157441252/6cde5680-3d8e-4478-852d-c6006767b63e">
4. Clicked save

### Craft CMS version

5.0.2

### Plugin version

5.0.0-beta.1

### Multi-site?

no

### Additional context

I did get around this by adding in null as a second parameter for the time being:
"$value = $this->normalizeValue($this->defaultValue(), null);"
on Line 153 in Buttons.php

**Comment by engram-design** [comment]
Should be fixed in [5.0.0-beta.2](https://github.com/verbb/buttonbox/releases/tag/5.0.0-beta.2)
